# Generated by Django 4.1.3 on 2022-11-22 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, upload_to='test/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 3, 37, 40, 969693)),
        ),
    ]
