# Generated by Django 4.1.3 on 2022-11-22 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorageapp', '0002_alter_files_file_alter_files_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='file',
            new_name='path',
        ),
        migrations.AlterField(
            model_name='files',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 3, 40, 37, 434045)),
        ),
    ]
