# Generated by Django 4.1.3 on 2022-11-22 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorageapp', '0003_rename_file_files_path_alter_files_uploaded_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 10, 26, 42, 909333)),
        ),
    ]
