# Generated by Django 4.1.3 on 2022-11-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbookapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='phone',
            name='contact of user',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='user_id',
        ),
    ]
