# Generated by Django 4.1.3 on 2022-11-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addressbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressbookapp.contact'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressbookapp.contact'),
        ),
    ]
