# Generated by Django 4.1.3 on 2022-11-14 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addressbookapp', '0002_remove_phone_contact of user_remove_contact_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneToContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressbookapp.contact')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressbookapp.phone')),
            ],
        ),
    ]
