# Generated by Django 4.1.3 on 2022-11-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbookapp', '0006_alter_email_email_alter_phone_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
